version: "3.9"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: demo
    volumes:
      - .volumes/mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  # Run with `docker-compose --profile elasticsearch up`
  elasticsearch:
    image: elasticsearch:7.17.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      cluster.name: elastic-cluster
    profiles:
      - elasticsearch
    volumes:
      - .volumes/elasticsearch:/usr/share/elasticsearch/data