
spring:
  application:
    name: Contented
  sleuth:
    reactor:
      instrumentation-type: manual
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: demo
      username: root
      password: example
logging:
  level:
    root: INFO