
spring:
  application:
    name: Contented
  sleuth:
    reactor:
      instrumentation-type: manual
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: demo
      username: root
      password: example
    elasticsearch:
      client:
        reactive:
          endpoints: ${ELASTIC_HOST:localhost}:%{ELASTIC_PORT:9200}
logging:
  level:
    root: INFO